# This file is auto-generated by scripts/generate_choice_constraints.py.
# Do not edit manually.

CHOICE_CONSTRAINTS = {
    "Account": [
        {
            "options": [
                ["account_beneficiary", "servicing_party"],
                ["servicing_party"],
            ],
            "required": True,
        },
    ],
    "AccrualOptionChange": [
        {
            "options": [
                [
                    "fixed_rate_option",
                    "floating_rate_option",
                    "legacy_floating_rate_option",
                    "loan_contract_reference",
                ],
                ["accruing_pik_option"],
                ["lc_option", "letter_of_credit_reference"],
            ],
            "required": True,
        },
        {
            "options": [
                ["fixed_rate_option"],
                ["floating_rate_option"],
                ["legacy_floating_rate_option"],
            ],
            "required": True,
        },
    ],
    "AdditionalData": [
        {
            "options": [
                ["string"],
                ["hexadecimal_binary"],
                ["base64_binary"],
                ["original_message"],
            ],
            "required": True,
        },
    ],
    "AdjustableDate2": [
        {
            "options": [
                ["date_adjustments"],
                ["date_adjustments_reference"],
            ],
            "required": False,
        },
    ],
    "AdjustableDateOrRelativeDateSequence": [
        {
            "options": [
                ["adjustable_date"],
                ["relative_date_sequence"],
            ],
            "required": True,
        },
    ],
    "AdjustableDatesOrRelativeDateOffset": [
        {
            "options": [
                ["adjustable_dates"],
                ["relative_date"],
            ],
            "required": True,
        },
    ],
    "AdjustableOrAdjustedDate": [
        {
            "options": [
                ["unadjusted_date", "date_adjustments", "adjusted_date"],
                ["adjusted_date"],
            ],
            "required": True,
        },
    ],
    "AdjustableOrRelativeDate": [
        {
            "options": [
                ["adjustable_date"],
                ["relative_date"],
            ],
            "required": True,
        },
    ],
    "AdjustableOrRelativeDates": [
        {
            "options": [
                ["adjustable_dates"],
                ["relative_dates"],
            ],
            "required": True,
        },
    ],
    "AdjustableRelativeOrPeriodicDates": [
        {
            "options": [
                ["adjustable_dates"],
                ["relative_date_sequence"],
                ["periodic_dates"],
            ],
            "required": True,
        },
    ],
    "AdjustableRelativeOrPeriodicDates2": [
        {
            "options": [
                ["adjustable_dates"],
                ["relative_dates"],
                ["periodic_dates"],
            ],
            "required": True,
        },
    ],
    "Allocation": [
        {
            "options": [
                ["allocated_fraction"],
                ["allocated_notional"],
            ],
            "required": True,
        },
    ],
    "ApplicableAssets": [
        {
            "options": [
                ["deal_identifier"],
                ["facility_identifier"],
                ["facility_type"],
            ],
            "required": True,
        },
    ],
    "ApplicableCommunicationDetails": [
        {
            "options": [
                ["related_person"],
                ["related_business_unit"],
            ],
            "required": True,
        },
    ],
    "ApplicableTransactions": [
        {
            "options": [
                ["applicable_transaction_type"],
                ["all_transactions"],
            ],
            "required": True,
        },
    ],
    "ApprovalParties": [
        {
            "options": [
                ["eligible_party"],
                ["ineligible_party", "ineligible_reason"],
            ],
            "required": True,
        },
    ],
    "ApprovalStatusNotification": [
        {
            "options": [
                ["trade"],
                ["trade_identifier"],
            ],
            "required": True,
        },
    ],
    "ApprovalVoteDecision": [
        {
            "options": [
                ["document_vote_decision"],
                ["description"],
            ],
            "required": False,
        },
    ],
    "AveragingPeriod": [
        {
            "options": [
                ["averaging_date_times"],
                ["averaging_observations"],
            ],
            "required": False,
        },
    ],
    "BasketReferenceInformation": [
        {
            "options": [
                ["nth_to_default", "mth_to_default"],
                ["tranche"],
            ],
            "required": False,
        },
    ],
    "BondOptionStrike": [
        {
            "options": [
                ["reference_swap_curve"],
                ["price"],
            ],
            "required": True,
        },
    ],
    "Calculation": [
        {
            "options": [
                ["notional_schedule"],
                ["fx_linked_notional_schedule"],
            ],
            "required": True,
        },
        {
            "options": [
                ["fixed_rate_schedule", "future_value_notional"],
                ["floating_rate_calculation"],
                ["inflation_rate_calculation"],
            ],
            "required": True,
        },
    ],
    "CalculationAgent": [
        {
            "options": [
                ["calculation_agent_party_reference"],
                ["calculation_agent_party"],
            ],
            "required": True,
        },
    ],
    "CalculationFromObservation": [
        {
            "options": [
                ["closing_level"],
                ["expiring_level"],
            ],
            "required": True,
        },
        {
            "options": [
                ["initial_level", "initial_level_source"],
                ["initial_level_source"],
            ],
            "required": True,
        },
    ],
    "CalculationParameters": [
        {
            "options": [
                ["lookback"],
                ["observation_shift"],
                ["lockout"],
            ],
            "required": False,
        },
    ],
    "CalculationPeriod": [
        {
            "options": [
                ["notional_amount"],
                ["fx_linked_notional_amount"],
            ],
            "required": True,
        },
        {
            "options": [
                ["floating_rate_definition"],
                ["fixed_rate"],
            ],
            "required": True,
        },
    ],
    "CalculationPeriodAmount": [
        {
            "options": [
                ["calculation"],
                ["known_amount_schedule"],
            ],
            "required": True,
        },
    ],
    "CalculationPeriodDates": [
        {
            "options": [
                ["effective_date"],
                ["relative_effective_date"],
            ],
            "required": True,
        },
        {
            "options": [
                ["termination_date"],
                ["relative_termination_date"],
            ],
            "required": True,
        },
    ],
    "CashSettlement": [
        {
            "options": [
                ["mid_market_valuation", "replacement_value"],
                [
                    "par_yield_curve_unadjusted_method",
                    "collateralized_cash_price_method",
                ],
                [
                    "cash_price_method",
                    "cash_price_alternate_method",
                    "par_yield_curve_adjusted_method",
                    "zero_coupon_yield_adjusted_method",
                    "cross_currency_method",
                ],
            ],
            "required": False,
        },
    ],
    "CashSettlementPaymentDate": [
        {
            "options": [
                ["adjustable_dates"],
                ["relative_date"],
                ["business_date_range"],
            ],
            "required": True,
        },
    ],
    "CashflowNotional": [
        {
            "options": [
                ["currency"],
                ["units"],
            ],
            "required": True,
        },
    ],
    "ClearingEligibility": [
        {
            "options": [
                ["additional_event"],
                ["de_clear"],
                ["party_trade_identifier"],
            ],
            "required": False,
        },
    ],
    "ClearingStatusItem": [
        {
            "options": [
                ["trade_identifier"],
                ["trade_reference_information"],
                ["trade"],
                ["trade_package"],
            ],
            "required": True,
        },
    ],
    "CoalAttributeDecimal": [
        {
            "options": [
                ["standard_content", "rejection_limit"],
                ["rejection_limit"],
            ],
            "required": True,
        },
    ],
    "CoalAttributePercentage": [
        {
            "options": [
                ["standard_content", "rejection_limit"],
                ["rejection_limit"],
            ],
            "required": True,
        },
    ],
    "CoalDelivery": [
        {
            "options": [
                ["delivery_point"],
                ["delivery_at_source"],
            ],
            "required": True,
        },
    ],
    "CoalProduct": [
        {
            "options": [
                ["type"],
                ["coal_product_specifications"],
            ],
            "required": True,
        },
    ],
    "CoalProductSpecifications": [
        {
            "options": [
                ["standard_quality"],
                ["standard_quality_schedule"],
            ],
            "required": True,
        },
    ],
    "CollateralPortfolio": [
        {
            "options": [
                ["cash"],
                ["non_cash"],
            ],
            "required": False,
        },
    ],
    "CollateralPosition": [
        {
            "options": [
                ["margin_ratio"],
                ["haircut"],
            ],
            "required": False,
        },
    ],
    "CollateralValuation": [
        {
            "options": [
                ["nominal_amount", "quantity", "accruals_amount"],
                ["number_of_units", "unit_price"],
            ],
            "required": True,
        },
    ],
    "CommodityAmericanExercise": [
        {
            "options": [
                ["latest_exercise_time"],
                ["latest_exercise_time_determination"],
            ],
            "required": False,
        },
    ],
    "CommodityBasketOption": [
        {
            "options": [
                ["strike_price_underlying_reference"],
                ["strike_price_basket_reference"],
            ],
            "required": True,
        },
        {
            "options": [
                ["strike_price_per_unit", "strike_price_per_unit_schedule"],
                [
                    "floating_strike_price_per_unit",
                    "floating_strike_price_per_unit_schedule",
                ],
            ],
            "required": True,
        },
    ],
    "CommodityDeliveryPeriods": [
        {
            "options": [
                ["periods"],
                ["periods_schedule"],
                [
                    "calculation_periods_reference",
                    "calculation_periods_schedule_reference",
                    "calculation_periods_dates_reference",
                ],
            ],
            "required": True,
        },
    ],
    "CommodityDigitalExercise": [
        {
            "options": [
                ["american_exercise"],
                ["european_exercise"],
            ],
            "required": True,
        },
    ],
    "CommodityDigitalOption": [
        {
            "options": [
                ["notional_amount"],
                ["notional_quantity", "total_notional_quantity"],
            ],
            "required": True,
        },
    ],
    "CommodityExercise": [
        {
            "options": [
                ["american_exercise"],
                ["european_exercise"],
            ],
            "required": True,
        },
    ],
    "CommodityExerciseBasket": [
        {
            "options": [
                ["american_exercise"],
                ["european_exercise"],
            ],
            "required": True,
        },
    ],
    "CommodityFixedPriceSchedule": [
        {
            "options": [
                ["fixed_price_step"],
                ["worldscale_rate_step"],
                ["contract_rate_step"],
                ["settlement_periods_price_schedule"],
            ],
            "required": True,
        },
    ],
    "CommodityForward": [
        {
            "options": [
                ["fixed_leg"],
                ["average_price_leg"],
            ],
            "required": True,
        },
    ],
    "CommodityFx": [
        {
            "options": [
                ["fixing_time"],
                [
                    "fx_observation_dates",
                    "fixing_time",
                    "day_type",
                    "day_distribution",
                    "day_count",
                    "day_of_week",
                    "day_number",
                    "business_day_convention",
                    "lag",
                    "lag_reference",
                    "calculation_periods_reference",
                    "calculation_periods_schedule_reference",
                    "calculation_periods_dates_reference",
                ],
            ],
            "required": False,
        },
        {
            "options": [
                ["fx_observation_dates"],
                [
                    "day_type",
                    "day_distribution",
                    "day_count",
                    "day_of_week",
                    "day_number",
                    "business_day_convention",
                    "lag",
                    "lag_reference",
                    "calculation_periods_reference",
                    "calculation_periods_schedule_reference",
                    "calculation_periods_dates_reference",
                ],
            ],
            "required": True,
        },
    ],
    "CommodityInterestLeg": [
        {
            "options": [
                ["notional_amount"],
                ["notional_amount_reference"],
            ],
            "required": True,
        },
    ],
    "CommodityMarketDisruption": [
        {
            "options": [
                ["market_disruption_events", "additional_market_disruption_event"],
                ["market_disruption_event"],
            ],
            "required": True,
        },
        {
            "options": [
                ["disruption_fallbacks"],
                ["disruption_fallback"],
            ],
            "required": False,
        },
    ],
    "CommodityNotionalQuantitySchedule": [
        {
            "options": [
                ["notional_step"],
                ["settlement_periods_notional_quantity_schedule"],
            ],
            "required": True,
        },
    ],
    "CommodityOption": [
        {
            "options": [
                ["commodity", "american_exercise"],
                ["commodity", "bermuda_exercise"],
                ["commodity", "european_exercise"],
                ["commodity_swap", "commodity_forward", "physical_exercise"],
                [
                    "effective_date",
                    "weather_notional_amount",
                    "american_exercise",
                    "weather_index_strike_level",
                    "calculation",
                    "weather_index_data",
                ],
                [
                    "effective_date",
                    "weather_notional_amount",
                    "bermuda_exercise",
                    "weather_index_strike_level",
                    "calculation",
                    "weather_index_data",
                ],
                [
                    "effective_date",
                    "weather_notional_amount",
                    "european_exercise",
                    "weather_index_strike_level",
                    "calculation",
                    "weather_index_data",
                ],
            ],
            "required": True,
        },
    ],
    "CommodityPhysicalAmericanExercise": [
        {
            "options": [
                ["commencement_dates", "expiration_dates"],
                ["relative_commencement_dates", "relative_expiration_dates"],
            ],
            "required": True,
        },
    ],
    "CommodityPhysicalEuropeanExercise": [
        {
            "options": [
                ["expiration_date"],
                ["expiration_dates"],
                ["relative_expiration_dates"],
            ],
            "required": True,
        },
    ],
    "CommodityPhysicalExercise": [
        {
            "options": [
                ["american_exercise"],
                ["european_exercise"],
            ],
            "required": True,
        },
    ],
    "CommodityPricingDates": [
        {
            "options": [
                [
                    "lag",
                    "business_calendar",
                    "calendar_source",
                    "settlement_periods",
                    "settlement_periods_reference",
                    "day_type",
                    "day_distribution",
                    "day_count",
                    "day_of_week",
                    "day_number",
                    "business_day_convention",
                ],
                ["pricing_dates"],
            ],
            "required": True,
        },
        {
            "options": [
                [
                    "business_calendar",
                    "calendar_source",
                    "day_type",
                    "day_distribution",
                    "day_count",
                    "day_of_week",
                    "day_number",
                    "business_day_convention",
                ],
                ["settlement_periods"],
                ["settlement_periods_reference"],
            ],
            "required": True,
        },
    ],
    "CommodityRelativePaymentDates": [
        {
            "options": [
                ["pay_relative_to"],
                ["pay_relative_to_event"],
            ],
            "required": True,
        },
    ],
    "CommodityReturnLeg": [
        {
            "options": [
                ["notional_amount"],
                ["notional_amount_reference"],
            ],
            "required": True,
        },
    ],
    "CommodityStartingDate": [
        {
            "options": [
                ["date_relative_to"],
                ["adjustable_date"],
            ],
            "required": True,
        },
    ],
    "CommodityTrigger": [
        {
            "options": [
                ["level_quantity", "level_unit"],
                ["level_percentage"],
                ["level_price"],
            ],
            "required": True,
        },
    ],
    "CommodityValuationDates": [
        {
            "options": [
                [
                    "lag",
                    "business_calendar",
                    "calendar_source",
                    "settlement_periods",
                    "settlement_periods_reference",
                    "day_type",
                    "day_distribution",
                    "day_count",
                    "day_of_week",
                    "day_number",
                    "business_day_convention",
                ],
                ["valuation_dates"],
            ],
            "required": True,
        },
        {
            "options": [
                [
                    "business_calendar",
                    "calendar_source",
                    "day_type",
                    "day_distribution",
                    "day_count",
                    "day_of_week",
                    "day_number",
                    "business_day_convention",
                ],
                ["settlement_periods"],
                ["settlement_periods_reference"],
            ],
            "required": True,
        },
    ],
    "CommodityVarianceLeg": [
        {
            "options": [
                ["notional_amount"],
                ["notional_amount_reference"],
            ],
            "required": True,
        },
        {
            "options": [
                ["variance_strike_price"],
                ["volatility_strike_price"],
            ],
            "required": True,
        },
    ],
    "CompoundingRate": [
        {
            "options": [
                ["interest_leg_rate"],
                ["specific_rate"],
            ],
            "required": True,
        },
    ],
    "CompressionActivity": [
        {
            "options": [
                ["replacement_trade_identifier", "originating_trade_identifier"],
                ["replacement_trade_id", "originating_trade_id"],
            ],
            "required": False,
        },
    ],
    "ConfirmationAgreed": [
        {
            "options": [
                ["trade_package", "originating_event", "trade"],
                [
                    "amendment",
                    "increase",
                    "terminating_event",
                    "termination",
                    "novation",
                    "withdrawal",
                    "observation",
                    "reset",
                ],
                ["change"],
                ["option_exercise", "option_expiry", "option_event"],
                ["additional_event"],
            ],
            "required": False,
        },
    ],
    "ConfirmationDisputed": [
        {
            "options": [
                ["trade_package", "originating_event", "trade"],
                [
                    "amendment",
                    "increase",
                    "terminating_event",
                    "termination",
                    "novation",
                    "withdrawal",
                    "observation",
                    "reset",
                ],
                ["change"],
                ["option_exercise", "option_expiry", "option_event"],
                ["additional_event"],
            ],
            "required": False,
        },
    ],
    "ConfirmationRetracted": [
        {
            "options": [
                ["additional_event"],
                ["option_exercise"],
            ],
            "required": False,
        },
    ],
    "ConfirmationStatus": [
        {
            "options": [
                ["asserted_event", "proposed_match"],
                ["alleged_event"],
            ],
            "required": True,
        },
    ],
    "ContractIdentifier": [
        {
            "options": [
                ["contract_id"],
                ["versioned_contract_id"],
            ],
            "required": True,
        },
    ],
    "CovenantObligationIdentifier": [
        {
            "options": [
                ["covenant_obligation_id"],
                ["versioned_covenant_obligation_id"],
            ],
            "required": True,
        },
    ],
    "CreditDefaultSwap": [
        {
            "options": [
                ["cash_settlement_terms"],
                ["physical_settlement_terms"],
            ],
            "required": False,
        },
    ],
    "CreditLimitUtilizationPosition": [
        {
            "options": [
                ["short", "long", "global"],
                ["global"],
            ],
            "required": True,
        },
    ],
    "CreditOptionStrike": [
        {
            "options": [
                ["spread"],
                ["price"],
                ["strike_reference"],
            ],
            "required": True,
        },
    ],
    "DealSummary": [
        {
            "options": [
                ["currency"],
                ["issued_amount", "current_deal_amount"],
            ],
            "required": False,
        },
    ],
    "DeliverableObligations": [
        {
            "options": [
                ["full_faith_and_credit_ob_liability"],
                ["general_fund_obligation_liability"],
                ["revenue_obligation_liability"],
            ],
            "required": False,
        },
    ],
    "DividendConditions": [
        {
            "options": [
                ["dividend_period_effective_date", "dividend_period_end_date"],
                ["dividend_period"],
            ],
            "required": True,
        },
    ],
    "DividendPaymentDate": [
        {
            "options": [
                ["dividend_date_reference", "payment_date_offset"],
                ["adjustable_date"],
            ],
            "required": True,
        },
    ],
    "DividendPayout": [
        {
            "options": [
                [
                    "dividend_payout_ratio",
                    "dividend_payout_ratio_cash",
                    "dividend_payout_ratio_non_cash",
                ],
                ["dividend_payout_conditions"],
            ],
            "required": True,
        },
    ],
    "DividendSwapOptionTransactionSupplement": [
        {
            "options": [
                ["option_entitlement"],
                ["multiplier"],
            ],
            "required": False,
        },
    ],
    "Documentation": [
        {
            "options": [
                ["master_confirmation"],
                ["broker_confirmation"],
            ],
            "required": False,
        },
    ],
    "EarlyTerminationProvision": [
        {
            "options": [
                [
                    "mandatory_early_termination",
                    "mandatory_early_termination_date_tenor",
                    "optional_early_termination",
                    "optional_early_termination_parameters",
                ],
                ["optional_early_termination", "optional_early_termination_parameters"],
            ],
            "required": True,
        },
    ],
    "ElectricityDelivery": [
        {
            "options": [
                [
                    "delivery_point",
                    "delivery_type",
                    "transmission_contingency",
                    "interconnection_point",
                ],
                ["delivery_zone", "electing_party_reference"],
            ],
            "required": True,
        },
    ],
    "ElectricityDeliveryType": [
        {
            "options": [
                ["firm"],
                ["non_firm"],
                ["system_firm"],
                ["unit_firm"],
            ],
            "required": True,
        },
    ],
    "ElectricityPhysicalQuantity": [
        {
            "options": [
                ["physical_quantity"],
                ["physical_quantity_schedule"],
            ],
            "required": True,
        },
    ],
    "EquityExerciseValuationSettlement": [
        {
            "options": [
                ["equity_european_exercise"],
                ["equity_american_exercise"],
                ["equity_bermuda_exercise"],
            ],
            "required": True,
        },
        {
            "options": [
                ["automatic_exercise", "make_whole_provisions"],
                ["pre_payment"],
            ],
            "required": True,
        },
    ],
    "EquityOptionTransactionSupplement": [
        {
            "options": [
                ["option_entitlement"],
                ["multiplier"],
            ],
            "required": False,
        },
    ],
    "EquityStrike": [
        {
            "options": [
                ["strike_price"],
                ["strike_percentage", "strike_determination_date"],
            ],
            "required": True,
        },
    ],
    "EquityValuation": [
        {
            "options": [
                ["valuation_date"],
                ["valuation_dates"],
            ],
            "required": False,
        },
        {
            "options": [
                ["futures_price_valuation"],
                ["options_price_valuation"],
            ],
            "required": False,
        },
    ],
    "EventIdentifier": [
        {
            "options": [
                ["correlation_id", "sequence_number"],
                ["trade_identifier"],
            ],
            "required": True,
        },
    ],
    "EventProposedMatch": [
        {
            "options": [
                ["trade_package", "originating_event", "trade"],
                [
                    "amendment",
                    "increase",
                    "terminating_event",
                    "termination",
                    "novation",
                    "withdrawal",
                    "observation",
                    "reset",
                ],
                ["change"],
                ["option_exercise", "option_expiry", "option_event"],
                ["additional_event"],
            ],
            "required": True,
        },
    ],
    "EventsChoice": [
        {
            "options": [
                ["trade_package", "originating_event", "trade"],
                [
                    "amendment",
                    "increase",
                    "terminating_event",
                    "termination",
                    "novation",
                    "withdrawal",
                    "observation",
                    "reset",
                ],
                ["change"],
                ["option_exercise", "option_expiry", "option_event"],
                ["additional_event"],
            ],
            "required": True,
        },
    ],
    "ExchangeTradedContractUnderlyer": [
        {
            "options": [
                ["floating_rate_index", "index_tenor"],
                ["quoted_currency_pair"],
                ["basket"],
                ["bond"],
                ["cash"],
                ["commodity"],
                ["convertible_bond"],
                ["equity"],
                ["exchange_traded_fund"],
                ["future"],
                ["index"],
                ["loan"],
                ["mortgage"],
                ["mutual_fund"],
                ["option"],
                ["security"],
                ["warrant"],
            ],
            "required": True,
        },
    ],
    "ExecutionAdvice": [
        {
            "options": [
                ["trade_package", "originating_event", "trade"],
                [
                    "amendment",
                    "increase",
                    "terminating_event",
                    "termination",
                    "novation",
                    "withdrawal",
                    "observation",
                    "reset",
                ],
                ["change"],
                ["option_exercise", "option_expiry", "option_event"],
                ["additional_event"],
            ],
            "required": True,
        },
    ],
    "ExecutionAdviceRetracted": [
        {
            "options": [
                ["trade_package", "originating_event", "trade"],
                [
                    "amendment",
                    "increase",
                    "terminating_event",
                    "termination",
                    "novation",
                    "withdrawal",
                    "observation",
                    "reset",
                ],
                ["change"],
                ["option_exercise", "option_expiry", "option_event"],
                ["additional_event"],
            ],
            "required": False,
        },
    ],
    "ExecutionNotification": [
        {
            "options": [
                ["trade_package", "originating_event", "trade"],
                ["amendment"],
                ["option_exercise", "option_expiry", "option_event"],
                ["additional_event"],
            ],
            "required": True,
        },
    ],
    "ExecutionRetracted": [
        {
            "options": [
                ["additional_event"],
                ["option_exercise"],
            ],
            "required": False,
        },
    ],
    "ExerciseFee": [
        {
            "options": [
                ["fee_amount"],
                ["fee_rate"],
            ],
            "required": True,
        },
    ],
    "ExerciseFeeSchedule": [
        {
            "options": [
                ["fee_amount_schedule"],
                ["fee_rate_schedule"],
            ],
            "required": True,
        },
    ],
    "ExerciseProcedure": [
        {
            "options": [
                ["manual_exercise"],
                ["automatic_exercise"],
            ],
            "required": True,
        },
    ],
    "ExerciseProcedureOption": [
        {
            "options": [
                ["manual_exercise"],
                ["automatic_exercise"],
            ],
            "required": True,
        },
    ],
    "ExtraordinaryEvents": [
        {
            "options": [
                ["additional_disruption_events"],
                ["failure_to_deliver"],
            ],
            "required": True,
        },
    ],
    "FallbackRate": [
        {
            "options": [
                ["effective_date"],
                [
                    "floating_rate_index",
                    "effective_date",
                    "calculation_parameters",
                    "spread_adjustment",
                ],
            ],
            "required": True,
        },
    ],
    "FeaturePayment": [
        {
            "options": [
                ["level_percentage"],
                ["amount"],
            ],
            "required": True,
        },
    ],
    "FeeLeg": [
        {
            "options": [
                ["initial_payment", "single_payment", "periodic_payment"],
                ["periodic_payment"],
            ],
            "required": True,
        },
        {
            "options": [
                ["initial_payment"],
                ["single_payment"],
            ],
            "required": True,
        },
    ],
    "FloatingLegCalculation": [
        {
            "options": [
                ["spread"],
                ["spread_schedule"],
                ["spread_percentage"],
            ],
            "required": False,
        },
    ],
    "Future": [
        {
            "options": [
                ["maturity"],
                ["contract_year_month"],
            ],
            "required": False,
        },
    ],
    "FxAccrualBarrier": [
        {
            "options": [
                ["observable_reference"],
                ["quoted_currency_pair", "information_source"],
            ],
            "required": False,
        },
    ],
    "FxAccrualLeverage": [
        {
            "options": [
                ["ratio"],
                ["notional_amount", "counter_currency_amount"],
            ],
            "required": True,
        },
    ],
    "FxAccrualLinearPayoffRegion": [
        {
            "options": [
                ["strike", "counter_currency_amount"],
                ["average_strike"],
            ],
            "required": True,
        },
    ],
    "FxAccrualOption": [
        {
            "options": [
                ["strike", "counter_currency_amount"],
                ["average_strike"],
            ],
            "required": True,
        },
    ],
    "FxAccrualRegion": [
        {
            "options": [
                ["start_date", "end_date"],
                ["end_date"],
            ],
            "required": False,
        },
        {
            "options": [
                ["accrual_factor"],
                ["notional_amount", "counter_currency_amount"],
            ],
            "required": False,
        },
    ],
    "FxAccrualSettlementPeriodPayoff": [
        {
            "options": [
                ["strike", "counter_currency_amount"],
                ["average_strike_fixing_dates"],
            ],
            "required": True,
        },
    ],
    "FxAsianFeature": [
        {
            "options": [
                [
                    "observation_schedule",
                    "rate_observation",
                    "rate_observation_quote_basis",
                ],
                ["rate_observation", "rate_observation_quote_basis"],
            ],
            "required": True,
        },
    ],
    "FxBarrierFeature": [
        {
            "options": [
                [
                    "observation_start_date",
                    "observation_start_time",
                    "observation_end_date",
                    "observation_end_time",
                ],
                ["observation_point"],
            ],
            "required": False,
        },
    ],
    "FxCashSettlement": [
        {
            "options": [
                ["fixing"],
                ["rate_source_fixing"],
            ],
            "required": False,
        },
    ],
    "FxCashSettlementSimple": [
        {
            "options": [
                ["fixing"],
                ["rate_source_fixing"],
            ],
            "required": False,
        },
    ],
    "FxConversion": [
        {
            "options": [
                ["amount_relative_to"],
                ["fx_rate"],
            ],
            "required": True,
        },
    ],
    "FxDigitalOption": [
        {
            "options": [
                ["american_exercise", "touch"],
                ["european_exercise", "trigger"],
            ],
            "required": True,
        },
    ],
    "FxFeature": [
        {
            "options": [
                ["composite"],
                ["quanto"],
                ["cross_currency"],
            ],
            "required": True,
        },
    ],
    "FxFixingDate": [
        {
            "options": [
                ["date_relative_to_payment_dates"],
                ["date_relative_to_calculation_period_dates"],
            ],
            "required": True,
        },
    ],
    "FxFixingSchedule": [
        {
            "options": [
                ["date_adjustments", "fixing_date"],
                [
                    "number_of_fixings",
                    "fixing_date",
                    "start_date",
                    "end_date",
                    "observation_frequency",
                    "date_adjustments",
                    "day_type",
                ],
            ],
            "required": True,
        },
        {
            "options": [
                ["number_of_fixings"],
                ["fixing_date"],
            ],
            "required": False,
        },
    ],
    "FxFixingScheduleSimple": [
        {
            "options": [
                ["start_date", "end_date"],
                ["end_date"],
            ],
            "required": True,
        },
    ],
    "FxKnockoutLevel": [
        {
            "options": [
                ["amount"],
                ["intrinsic_value"],
            ],
            "required": True,
        },
    ],
    "FxOption": [
        {
            "options": [
                ["american_exercise"],
                ["european_exercise"],
            ],
            "required": True,
        },
    ],
    "FxOptionFeatures": [
        {
            "options": [
                ["asian", "barrier"],
                ["barrier"],
            ],
            "required": True,
        },
    ],
    "FxPerformanceSwap": [
        {
            "options": [
                ["valuation_date"],
                ["valuation_date_offset"],
            ],
            "required": False,
        },
    ],
    "FxRateObservable": [
        {
            "options": [
                ["information_source"],
                ["cross_rate"],
            ],
            "required": True,
        },
    ],
    "FxSchedule": [
        {
            "options": [
                ["date_adjustments", "adjusted_date"],
                [
                    "date_offset",
                    "adjusted_date",
                    "start_date",
                    "end_date",
                    "observation_frequency",
                    "date_adjustments",
                    "day_type",
                ],
            ],
            "required": True,
        },
        {
            "options": [
                [
                    "start_date",
                    "end_date",
                    "observation_frequency",
                    "date_adjustments",
                    "day_type",
                ],
                ["date_offset"],
            ],
            "required": True,
        },
    ],
    "FxSettlementRateSource": [
        {
            "options": [
                ["settlement_rate_option"],
                ["nonstandard_settlement_rate"],
            ],
            "required": True,
        },
    ],
    "FxTarget": [
        {
            "options": [
                ["knockout_level"],
                ["knockout_count"],
            ],
            "required": True,
        },
    ],
    "FxTargetConstantPayoff": [
        {
            "options": [
                ["payment"],
                ["fixing_adjustment"],
            ],
            "required": True,
        },
    ],
    "FxTargetKnockoutForward": [
        {
            "options": [
                ["constant_payoff_region"],
                ["linear_payoff_region"],
            ],
            "required": False,
        },
    ],
    "FxTargetLeverage": [
        {
            "options": [
                ["ratio"],
                ["notional_amount", "counter_currency_amount"],
            ],
            "required": True,
        },
    ],
    "FxTargetRebate": [
        {
            "options": [
                ["payment"],
                ["outstanding_gain"],
            ],
            "required": True,
        },
    ],
    "FxTouch": [
        {
            "options": [
                [
                    "observation_start_date",
                    "observation_start_time",
                    "observation_end_date",
                    "observation_end_time",
                ],
                ["observation_point"],
            ],
            "required": False,
        },
    ],
    "FxWeightedFixingSchedule": [
        {
            "options": [
                ["date_adjustments", "fixing"],
                [
                    "number_of_fixings",
                    "fixing",
                    "start_date",
                    "end_date",
                    "observation_frequency",
                    "date_adjustments",
                    "day_type",
                ],
            ],
            "required": True,
        },
        {
            "options": [
                ["number_of_fixings"],
                ["fixing"],
            ],
            "required": False,
        },
    ],
    "GasPhysicalQuantity": [
        {
            "options": [
                [
                    "physical_quantity",
                    "physical_quantity_schedule",
                    "total_physical_quantity",
                ],
                ["min_physical_quantity", "max_physical_quantity", "electing_party"],
            ],
            "required": True,
        },
    ],
    "GasProduct": [
        {
            "options": [
                ["calorific_value"],
                ["quality"],
            ],
            "required": False,
        },
    ],
    "GeneralTerms": [
        {
            "options": [
                ["reference_information"],
                ["index_reference_information"],
                ["basket_reference_information"],
            ],
            "required": True,
        },
    ],
    "GenericFrequency": [
        {
            "options": [
                ["payer_party_reference"],
                ["underlyer_reference"],
            ],
            "required": False,
        },
    ],
    "GenericProduct": [
        {
            "options": [
                [
                    "buyer_party_reference",
                    "buyer_account_reference",
                    "seller_party_reference",
                    "seller_account_reference",
                ],
                ["counterparty_reference"],
            ],
            "required": False,
        },
    ],
    "IndexReferenceInformation": [
        {
            "options": [
                ["index_name", "index_id"],
                ["index_id"],
            ],
            "required": True,
        },
    ],
    "InitialMarginCalculation": [
        {
            "options": [
                ["margin_ratio", "margin_ratio_threshold"],
                ["haircut", "haircut_threshold"],
            ],
            "required": True,
        },
    ],
    "InstrumentSet": [
        {
            "options": [
                ["basket"],
                ["bond"],
                ["cash"],
                ["commodity"],
                ["convertible_bond"],
                ["equity"],
                ["exchange_traded_fund"],
                ["future"],
                ["index"],
                ["loan"],
                ["mortgage"],
                ["mutual_fund"],
                ["option"],
                ["security"],
                ["warrant"],
                ["deposit"],
                ["fx"],
                ["rate_index"],
                ["simple_credit_default_swap"],
                ["simple_fra"],
                ["simple_ir_swap"],
            ],
            "required": True,
        },
    ],
    "InstrumentTradeQuantity": [
        {
            "options": [
                ["number"],
                ["nominal"],
            ],
            "required": True,
        },
    ],
    "InterestAccrualsMethod": [
        {
            "options": [
                ["floating_rate_calculation"],
                ["fixed_rate"],
            ],
            "required": True,
        },
    ],
    "InterestLegResetDates": [
        {
            "options": [
                ["reset_relative_to"],
                ["reset_frequency"],
            ],
            "required": True,
        },
    ],
    "KeyInfoType": [
        {
            "options": [
                ["key_name"],
                ["key_value"],
                ["retrieval_method"],
                ["x509_data"],
                ["pgp_data"],
                ["spki_data"],
                ["mgmt_data"],
            ],
            "required": True,
        },
    ],
    "KeyValueType": [
        {
            "options": [
                ["dsa_key_value"],
                ["rsa_key_value"],
            ],
            "required": True,
        },
    ],
    "Knock": [
        {
            "options": [
                ["knock_in", "knock_out"],
                ["knock_out"],
            ],
            "required": True,
        },
    ],
    "LegAmount": [
        {
            "options": [
                ["reference_amount"],
                ["formula"],
                ["encoded_description"],
            ],
            "required": True,
        },
    ],
    "LegalActionIdentifier": [
        {
            "options": [
                ["legal_action_id"],
                ["versioned_legal_action_id"],
            ],
            "required": True,
        },
    ],
    "LegalEntity": [
        {
            "options": [
                ["entity_name", "entity_id"],
                ["entity_id"],
            ],
            "required": True,
        },
    ],
    "LimitApplicable": [
        {
            "options": [
                ["amount_utilized"],
                ["utilization"],
            ],
            "required": False,
        },
    ],
    "Loan": [
        {
            "options": [
                ["borrower"],
                ["borrower_reference"],
            ],
            "required": False,
        },
    ],
    "LoanAllocationNotification": [
        {
            "options": [
                ["loan_allocation"],
                ["loan_allocation_confirmation"],
                ["loan_allocation_settlement"],
                ["loan_allocation_fee_due"],
                ["loan_allocation_fee_owed"],
                ["loan_allocation_settlement_date_availability"],
                ["loan_allocation_settlement_date_finalization"],
                ["settlement_task"],
            ],
            "required": True,
        },
        {
            "options": [
                [
                    "letter_of_credit_identifier",
                    "letter_of_credit_summary",
                    "letter_of_credit",
                ],
                ["contract_identifier", "contract_summary", "contract"],
            ],
            "required": False,
        },
    ],
    "LoanAllocationSettlementDateAvailability": [
        {
            "options": [
                ["specific_dates"],
                ["start_date", "end_date"],
                ["on_or_after_date"],
            ],
            "required": True,
        },
    ],
    "LoanBulkServicingNotification": [
        {
            "options": [
                ["accrual_option_change"],
                ["accruing_fee_change"],
                ["accruing_fee_expiry"],
                ["accruing_fee_payment"],
                ["accruing_pik_payment"],
                ["amendment_fee_payment"],
                ["commitment_adjustment"],
                ["default_rate_change"],
                ["default_rate_expiry"],
                ["facility_extension_fee_payment"],
                ["facility_prepayment"],
                ["facility_prepayment_fee_payment"],
                ["facility_termination"],
                ["funding_fee_payment"],
                ["mandatory_cost_rate_change"],
                ["mandatory_cost_rate_expiry"],
                ["misc_fee_payment"],
                ["penalty_rate_change"],
                ["penalty_rate_expiry"],
                ["upfront_fee_payment"],
                ["waiver_fee_payment"],
                ["lc_adjustment"],
                ["lc_fx_revaluation"],
                ["lc_issuance"],
                ["lc_issuance_fee_payment"],
                ["lc_rate_change"],
                ["lc_renewal"],
                ["lc_termination"],
                ["loan_contract_adjustment"],
                ["base_rate_set"],
                ["borrowing"],
                ["breakage_fee_payment"],
                ["interest_capitalization"],
                ["interest_payment"],
                ["legacy_interest_capitalization"],
                ["legacy_interest_payment"],
                ["maturity_change"],
                ["repayment"],
                ["rollover"],
            ],
            "required": True,
        },
        {
            "options": [
                [
                    "letter_of_credit_identifier",
                    "letter_of_credit_summary",
                    "letter_of_credit",
                ],
                ["contract_identifier", "contract_summary", "contract"],
            ],
            "required": False,
        },
    ],
    "LoanContract": [
        {
            "options": [
                ["fixed_rate_accrual"],
                ["floating_rate_accrual"],
                ["legacy_floating_rate_accrual"],
            ],
            "required": True,
        },
    ],
    "LoanCovenantObligation": [
        {
            "options": [
                ["deemed_covenant_reference"],
                [
                    "category",
                    "type",
                    "description",
                    "location",
                    "trigger_criteria",
                    "accounting_details",
                ],
            ],
            "required": True,
        },
        {
            "options": [
                ["description"],
                ["location"],
            ],
            "required": False,
        },
    ],
    "LoanCovenantObligationDateTriggerDetails": [
        {
            "options": [
                ["due_date"],
                ["frequency_type"],
            ],
            "required": True,
        },
    ],
    "LoanCovenantObligationSummary": [
        {
            "options": [
                ["deal_reference"],
                ["facility_reference"],
            ],
            "required": True,
        },
    ],
    "LoanCovenantObligationTriggerCriteriaDetails": [
        {
            "options": [
                ["date"],
                ["metric"],
                ["hybrid_criteria"],
            ],
            "required": True,
        },
    ],
    "LoanLegalActionNotification": [
        {
            "options": [
                ["accrual_option_change"],
                ["accruing_fee_change"],
                ["accruing_fee_expiry"],
                ["accruing_fee_payment"],
                ["accruing_pik_payment"],
                ["amendment_fee_payment"],
                ["commitment_adjustment"],
                ["default_rate_change"],
                ["default_rate_expiry"],
                ["facility_extension_fee_payment"],
                ["facility_prepayment"],
                ["facility_prepayment_fee_payment"],
                ["facility_termination"],
                ["funding_fee_payment"],
                ["mandatory_cost_rate_change"],
                ["mandatory_cost_rate_expiry"],
                ["misc_fee_payment"],
                ["penalty_rate_change"],
                ["penalty_rate_expiry"],
                ["upfront_fee_payment"],
                ["waiver_fee_payment"],
                ["lc_adjustment"],
                ["lc_fx_revaluation"],
                ["lc_issuance"],
                ["lc_issuance_fee_payment"],
                ["lc_rate_change"],
                ["lc_renewal"],
                ["lc_termination"],
                ["loan_contract_adjustment"],
                ["base_rate_set"],
                ["borrowing"],
                ["breakage_fee_payment"],
                ["interest_capitalization"],
                ["interest_payment"],
                ["legacy_interest_capitalization"],
                ["legacy_interest_payment"],
                ["maturity_change"],
                ["repayment"],
                ["rollover"],
                ["legal_action_task"],
                ["legal_action_status"],
                ["legal_action_approval_status"],
            ],
            "required": True,
        },
        {
            "options": [
                ["legal_action_identifier"],
                ["legal_action_summary"],
                ["legal_action"],
            ],
            "required": True,
        },
        {
            "options": [
                ["deal_identifier", "deal_summary"],
                ["facility_identifier", "facility_summary"],
                ["contract_identifier", "contract_summary", "contract"],
                [
                    "letter_of_credit_identifier",
                    "letter_of_credit_summary",
                    "letter_of_credit",
                ],
            ],
            "required": False,
        },
    ],
    "LoanLegalActionStatement": [
        {
            "options": [
                ["deal_identifier", "deal_summary"],
                ["deal"],
            ],
            "required": False,
        },
        {
            "options": [
                ["facility_identifier", "facility_summary"],
                ["delayed_draw"],
                ["letter_of_credit_facility"],
                ["revolver"],
                ["term_loan"],
            ],
            "required": False,
        },
    ],
    "LoanLegalActionSummary": [
        {
            "options": [
                ["deal_reference"],
                ["facility_reference"],
            ],
            "required": True,
        },
    ],
    "LoanLegalStructureAfter": [
        {
            "options": [
                ["deal_reference"],
                ["facility_reference"],
            ],
            "required": True,
        },
        {
            "options": [
                ["contract_reference"],
                ["letter_of_credit_reference"],
            ],
            "required": False,
        },
    ],
    "LoanLegalStructureBefore": [
        {
            "options": [
                ["deal_reference"],
                ["facility_reference"],
            ],
            "required": True,
        },
        {
            "options": [
                ["contract_reference"],
                ["letter_of_credit_reference"],
            ],
            "required": False,
        },
    ],
    "LoanTradeNotification": [
        {
            "options": [
                ["loan_trade"],
                ["loan_trade_confirmation"],
                ["loan_trade_fee_due"],
                ["loan_trade_fee_owed"],
                ["settlement_task"],
            ],
            "required": True,
        },
    ],
    "LoanTradingCostOfCarryAccrual": [
        {
            "options": [
                ["commencement_accrual"],
                ["settlement_period_accrual"],
            ],
            "required": True,
        },
    ],
    "LoanTradingEconomicBenefit": [
        {
            "options": [
                ["event_identifier"],
                ["commitment_adjustment"],
            ],
            "required": False,
        },
    ],
    "LoanTradingNonAccruingFee": [
        {
            "options": [
                ["non_accruing_feetype"],
                ["misc_fee_type"],
            ],
            "required": False,
        },
        {
            "options": [
                ["facility_reference"],
                ["loan_contract_reference"],
                ["letter_of_credit_reference"],
            ],
            "required": True,
        },
    ],
    "LoanTransferFee": [
        {
            "options": [
                ["paid_by", "total_amount"],
                ["transfer_fee_amounts"],
            ],
            "required": True,
        },
    ],
    "MaturityNotification": [
        {
            "options": [
                ["option_expiry"],
                ["trade_maturity"],
            ],
            "required": True,
        },
    ],
    "MidMarketValuation": [
        {
            "options": [
                ["indicative_quotations"],
                ["indicative_quotations_alternate"],
                ["calculation_agent_determination"],
            ],
            "required": True,
        },
    ],
    "MiscFeePayment": [
        {
            "options": [
                ["type"],
                ["description"],
            ],
            "required": True,
        },
    ],
    "Mortgage": [
        {
            "options": [
                ["insurer"],
                ["insurer_reference"],
            ],
            "required": False,
        },
    ],
    "MultipleExercise": [
        {
            "options": [
                ["maximum_notional_amount"],
                ["maximum_number_of_options"],
            ],
            "required": False,
        },
    ],
    "MutuallyAgreedClearinghouse": [
        {
            "options": [
                ["party_reference"],
                ["identifier"],
            ],
            "required": True,
        },
    ],
    "NoTouchLowerBarrierObservation": [
        {
            "options": [
                ["trigger_rate", "quoted_currency_pair", "minimum_observed_rate"],
                ["trigger_price", "minimum_observed_price"],
            ],
            "required": True,
        },
    ],
    "NoTouchRateObservation": [
        {
            "options": [
                ["lower_barrier", "upper_barrier"],
                ["upper_barrier"],
            ],
            "required": True,
        },
        {
            "options": [
                [
                    "exercise_side",
                    "settlement_type",
                    "cash_settlement",
                    "physical_settlement",
                    "payment",
                    "clearing_instructions",
                ],
                ["is_exercisable"],
            ],
            "required": True,
        },
        {
            "options": [
                ["settlement_type"],
                ["cash_settlement"],
                ["physical_settlement"],
            ],
            "required": True,
        },
    ],
    "NoTouchUpperBarrierObservation": [
        {
            "options": [
                ["trigger_rate", "quoted_currency_pair", "maximum_observed_rate"],
                ["trigger_price", "maximum_observed_price"],
            ],
            "required": True,
        },
    ],
    "NonDeliverableSettlement": [
        {
            "options": [
                ["fx_fixing_date"],
                ["fx_fixing_schedule"],
            ],
            "required": True,
        },
    ],
    "NotionalStepRule": [
        {
            "options": [
                ["notional_step_amount"],
                ["notional_step_rate", "step_relative_to"],
            ],
            "required": True,
        },
    ],
    "Obligations": [
        {
            "options": [
                ["full_faith_and_credit_ob_liability"],
                ["general_fund_obligation_liability"],
                ["revenue_obligation_liability"],
            ],
            "required": False,
        },
    ],
    "OilDelivery": [
        {
            "options": [
                ["pipeline"],
                ["transfer"],
            ],
            "required": True,
        },
        {
            "options": [
                ["absolute_tolerance"],
                ["percentage_tolerance"],
            ],
            "required": False,
        },
    ],
    "OptionBaseExtended": [
        {
            "options": [
                ["notional_reference"],
                ["notional_amount"],
            ],
            "required": False,
        },
    ],
    "OptionEvent": [
        {
            "options": [
                ["original_trade"],
                ["trade_identifier"],
            ],
            "required": True,
        },
        {
            "options": [
                ["knock_in"],
                ["knock_out"],
                ["touch"],
                ["no_touch"],
            ],
            "required": True,
        },
    ],
    "OptionExercise": [
        {
            "options": [
                ["original_trade"],
                ["trade_identifier"],
            ],
            "required": True,
        },
        {
            "options": [
                ["exercise_date", "exercise_time"],
                ["exercise_timing"],
            ],
            "required": True,
        },
        {
            "options": [
                ["settlement_type"],
                ["cash_settlement"],
                ["physical_settlement"],
            ],
            "required": False,
        },
    ],
    "OptionExerciseAmounts": [
        {
            "options": [
                [
                    "notional_reference",
                    "exercise_in_notional_amount",
                    "outstanding_notional_amount",
                ],
                [
                    "notional_schedule_reference",
                    "exercise_in_notional_schedule",
                    "outstanding_notional_schedule",
                ],
                [
                    "number_of_options_reference",
                    "exercise_in_number_of_options",
                    "outstanding_number_of_options",
                ],
                [
                    "number_of_units_reference",
                    "exercise_in_number_of_units",
                    "outstanding_number_of_units",
                ],
            ],
            "required": True,
        },
    ],
    "OptionExpiry": [
        {
            "options": [
                ["original_trade"],
                ["trade_identifier"],
            ],
            "required": True,
        },
    ],
    "OptionNumericStrike": [
        {
            "options": [
                ["strike_price"],
                ["strike_percentage"],
            ],
            "required": True,
        },
    ],
    "OutstandingContractsStatement": [
        {
            "options": [
                ["loan_contract"],
                ["letter_of_credit"],
            ],
            "required": True,
        },
    ],
    "OutstandingsPosition": [
        {
            "options": [
                ["loan_contract_reference"],
                ["letter_of_credit_reference"],
            ],
            "required": True,
        },
    ],
    "PGPDataType": [
        {
            "options": [
                ["pgp_key_id", "pgp_key_packet"],
                ["pgp_key_packet"],
            ],
            "required": True,
        },
    ],
    "Party": [
        {
            "options": [
                ["party_id", "party_name", "contact_info", "business_unit", "person"],
                ["group_type", "party_reference"],
            ],
            "required": True,
        },
    ],
    "PartyProfile": [
        {
            "options": [
                ["communication_details"],
                ["settlement_instruction_details"],
            ],
            "required": True,
        },
    ],
    "PartySelector": [
        {
            "options": [
                ["party_reference"],
                ["party_determination"],
            ],
            "required": True,
        },
    ],
    "PartyTradeIdentifier": [
        {
            "options": [
                ["allocation_trade_id"],
                ["resulting_trade_id"],
            ],
            "required": False,
        },
    ],
    "PartyTradeInformation": [
        {
            "options": [
                ["end_user_exception", "end_user_exception_reason"],
                ["end_user_exception_declaration"],
            ],
            "required": False,
        },
    ],
    "PaymentCalculationPeriod": [
        {
            "options": [
                ["calculation_period"],
                ["fixed_payment_amount"],
            ],
            "required": True,
        },
    ],
    "PaymentDates": [
        {
            "options": [
                ["calculation_period_dates_reference"],
                ["reset_dates_reference"],
                ["valuation_dates_reference"],
            ],
            "required": True,
        },
    ],
    "PaymentDetail": [
        {
            "options": [
                ["payment_amount"],
                ["payment_rule", "payment_amount"],
            ],
            "required": True,
        },
    ],
    "PeriodicPayment": [
        {
            "options": [
                ["fixed_amount"],
                ["fixed_amount_calculation"],
                ["floating_amount_calculation"],
            ],
            "required": True,
        },
    ],
    "Person": [
        {
            "options": [
                ["middle_name"],
                ["initial"],
            ],
            "required": False,
        },
    ],
    "PhysicalSettlement": [
        {
            "options": [
                ["resulting_trade_identifier"],
                ["resulting_trade"],
                ["bond_option"],
                ["credit_default_swap"],
                ["credit_default_swap_option"],
                ["commodity_basket_option"],
                ["commodity_digital_option"],
                ["commodity_forward"],
                ["commodity_option"],
                ["commodity_performance_swap"],
                ["commodity_swap"],
                ["commodity_swaption"],
                ["correlation_swap"],
                ["dividend_swap_option_transaction_supplement"],
                ["dividend_swap_transaction_supplement"],
                ["instrument_trade_details"],
                ["strategy"],
                ["return_swap"],
                ["broker_equity_option"],
                ["equity_forward"],
                ["equity_option"],
                ["equity_option_transaction_supplement"],
                ["fx_digital_option"],
                ["fx_flexible_forward"],
                ["fx_forward_volatility_agreement"],
                ["fx_option"],
                ["fx_single_leg"],
                ["fx_swap"],
                ["fx_variance_swap"],
                ["fx_volatility_swap"],
                ["term_deposit"],
                ["fx_accrual_digital_option"],
                ["fx_accrual_forward"],
                ["fx_accrual_option"],
                ["fx_range_accrual"],
                ["fx_target_knockout_forward"],
                ["generic_product"],
                ["bullet_payment"],
                ["cap_floor"],
                ["fra"],
                ["swap"],
                ["swaption"],
                ["repo"],
                ["equity_swap_transaction_supplement"],
                ["security_lending"],
                ["standard_product"],
                ["variance_option_transaction_supplement"],
                ["variance_swap"],
                ["variance_swap_transaction_supplement"],
                ["volatility_swap"],
                ["volatility_swap_transaction_supplement"],
            ],
            "required": True,
        },
    ],
    "PhysicalSettlementPeriod": [
        {
            "options": [
                ["business_days_not_specified"],
                ["business_days"],
                ["maximum_business_days"],
            ],
            "required": True,
        },
    ],
    "Portfolio": [
        {
            "options": [
                ["trade_id"],
                ["party_trade_identifier"],
            ],
            "required": False,
        },
    ],
    "PrepaidRate": [
        {
            "options": [
                ["fixed_rate"],
                ["floating_rate_index", "index_tenor"],
            ],
            "required": True,
        },
    ],
    "Price": [
        {
            "options": [
                [
                    "determination_method",
                    "gross_price",
                    "net_price",
                    "accrued_interest_price",
                    "fx_conversion",
                ],
                ["amount_relative_to"],
                ["gross_price", "net_price", "accrued_interest_price", "fx_conversion"],
            ],
            "required": True,
        },
    ],
    "PricingParameterDerivative": [
        {
            "options": [
                ["parameter_reference"],
                ["asset_reference"],
                ["term_point_reference"],
                ["pricing_structure_reference"],
                ["input_date_reference"],
            ],
            "required": True,
        },
    ],
    "PricingParameterShift": [
        {
            "options": [
                ["parameter_reference"],
                ["asset_reference"],
                ["term_point_reference"],
                ["pricing_structure_reference"],
            ],
            "required": True,
        },
    ],
    "PrincipalExchangeAmount": [
        {
            "options": [
                ["amount_relative_to"],
                ["determination_method"],
                ["principal_amount"],
            ],
            "required": True,
        },
    ],
    "ReferenceInformation": [
        {
            "options": [
                ["reference_obligation"],
                ["no_reference_obligation"],
                ["unknown_reference_obligation"],
            ],
            "required": True,
        },
    ],
    "ReferenceObligation": [
        {
            "options": [
                ["bond"],
                ["convertible_bond"],
                ["mortgage"],
                ["loan"],
            ],
            "required": True,
        },
        {
            "options": [
                ["primary_obligor"],
                ["primary_obligor_reference"],
            ],
            "required": False,
        },
        {
            "options": [
                ["guarantor"],
                ["guarantor_reference"],
            ],
            "required": False,
        },
    ],
    "ReferencePair": [
        {
            "options": [
                ["reference_obligation"],
                ["no_reference_obligation"],
            ],
            "required": True,
        },
    ],
    "ReplacementValue": [
        {
            "options": [
                ["firm_quotations"],
                ["calculation_agent_determination"],
            ],
            "required": True,
        },
    ],
    "Repo": [
        {
            "options": [
                [
                    "duration",
                    "calling_party",
                    "earliest_call_date",
                    "call_date",
                    "notice_period",
                    "party_notice_period",
                    "extension_style",
                    "extension_period",
                ],
                ["calling_party", "call_date", "notice_period", "party_notice_period"],
            ],
            "required": True,
        },
        {
            "options": [
                ["notice_period"],
                ["party_notice_period"],
            ],
            "required": False,
        },
        {
            "options": [
                ["notice_period"],
                ["party_notice_period"],
            ],
            "required": False,
        },
        {
            "options": [
                ["equity"],
                ["security"],
                ["tri_party"],
            ],
            "required": True,
        },
    ],
    "ReportingRegime": [
        {
            "options": [
                ["name", "supervisor_registration"],
                ["supervisor_registration"],
            ],
            "required": True,
        },
        {
            "options": [
                ["entity_classification"],
                ["party_entity_classification"],
            ],
            "required": False,
        },
    ],
    "ReportingRegimeIdentifier": [
        {
            "options": [
                ["name", "supervisor_registration"],
                ["supervisor_registration"],
            ],
            "required": True,
        },
    ],
    "RequestClearing": [
        {
            "options": [
                ["additional_event"],
                ["de_clear"],
            ],
            "required": True,
        },
    ],
    "RequestClearingEligibility": [
        {
            "options": [
                ["additional_event"],
                ["de_clear"],
            ],
            "required": True,
        },
    ],
    "RequestClearingRetracted": [
        {
            "options": [
                ["additional_event"],
                ["de_clear"],
            ],
            "required": False,
        },
    ],
    "RequestConfirmation": [
        {
            "options": [
                ["additional_event"],
                ["option_exercise"],
            ],
            "required": True,
        },
    ],
    "RequestConsent": [
        {
            "options": [
                ["additional_event"],
                ["de_clear"],
            ],
            "required": True,
        },
    ],
    "RequestConsentRetracted": [
        {
            "options": [
                ["additional_event"],
                ["de_clear"],
            ],
            "required": False,
        },
    ],
    "RequestExecution": [
        {
            "options": [
                ["additional_event"],
                ["option_exercise"],
            ],
            "required": True,
        },
    ],
    "RequestExecutionRetracted": [
        {
            "options": [
                ["additional_event"],
                ["option_exercise"],
            ],
            "required": False,
        },
    ],
    "Resource": [
        {
            "options": [
                ["string"],
                ["hexadecimal_binary"],
                ["base64_binary"],
                ["url"],
            ],
            "required": False,
        },
    ],
    "ReturnSwapNotional": [
        {
            "options": [
                ["relative_notional_amount"],
                ["relative_determination_method"],
                ["determination_method"],
                ["notional_amount"],
            ],
            "required": True,
        },
    ],
    "SecLendCollateralProvisions": [
        {
            "options": [
                ["collateral_type"],
                ["tri_party"],
            ],
            "required": True,
        },
        {
            "options": [
                ["margin_ratio"],
                ["haircut"],
            ],
            "required": True,
        },
    ],
    "SecurityLending": [
        {
            "options": [
                ["extension_style", "extension_period"],
                ["calling_party", "call_date", "notice_period", "party_notice_period"],
            ],
            "required": False,
        },
        {
            "options": [
                ["notice_period"],
                ["party_notice_period"],
            ],
            "required": False,
        },
        {
            "options": [
                ["fee", "rebate"],
                ["rebate"],
            ],
            "required": True,
        },
    ],
    "SensitivityDefinition": [
        {
            "options": [
                ["partial_derivative", "formula"],
                ["term"],
            ],
            "required": True,
        },
    ],
    "ServiceNotification": [
        {
            "options": [
                ["status"],
                ["processing_status"],
                ["advisory"],
            ],
            "required": True,
        },
    ],
    "SettlementInformation": [
        {
            "options": [
                ["standard_settlement_style"],
                ["settlement_instruction"],
            ],
            "required": True,
        },
    ],
    "SettlementPeriodFixingDates": [
        {
            "options": [
                ["fixing_date"],
                ["start_date", "end_date"],
                ["number_of_fixings"],
            ],
            "required": True,
        },
    ],
    "SettlementPeriodLeverage": [
        {
            "options": [
                ["ratio"],
                ["notional_amount", "counter_currency_amount"],
            ],
            "required": True,
        },
    ],
    "SettlementPeriods": [
        {
            "options": [
                ["exclude_holidays"],
                ["include_holidays"],
            ],
            "required": False,
        },
    ],
    "SettlementRateSource": [
        {
            "options": [
                ["information_source"],
                ["cash_settlement_reference_banks"],
            ],
            "required": True,
        },
    ],
    "SharedAmericanExercise": [
        {
            "options": [
                ["latest_exercise_time"],
                ["latest_exercise_time_determination"],
            ],
            "required": False,
        },
    ],
    "StartingDate": [
        {
            "options": [
                ["date_relative_to"],
                ["adjustable_date"],
            ],
            "required": True,
        },
    ],
    "StrategyFeature": [
        {
            "options": [
                ["strike_spread"],
                ["calendar_spread"],
            ],
            "required": True,
        },
    ],
    "StubCalculationPeriod": [
        {
            "options": [
                ["initial_stub", "final_stub"],
                ["final_stub"],
            ],
            "required": True,
        },
    ],
    "StubCalculationPeriodAmount": [
        {
            "options": [
                ["initial_stub", "final_stub"],
                ["final_stub"],
            ],
            "required": True,
        },
    ],
    "StubValue": [
        {
            "options": [
                ["floating_rate"],
                ["stub_rate"],
                ["stub_amount"],
            ],
            "required": True,
        },
    ],
    "Swaption": [
        {
            "options": [
                ["cash_settlement"],
                ["physical_settlement"],
            ],
            "required": False,
        },
    ],
    "SwaptionPhysicalSettlement": [
        {
            "options": [
                ["predetermined_clearing_organization_party_reference"],
                ["mutually_agreed_clearinghouse"],
            ],
            "required": False,
        },
    ],
    "TaskIdentifier": [
        {
            "options": [
                ["task_id"],
                ["versioned_task_id"],
            ],
            "required": True,
        },
    ],
    "TimeDimension": [
        {
            "options": [
                ["tenor"],
                ["date", "tenor"],
            ],
            "required": True,
        },
    ],
    "TouchRateObservation": [
        {
            "options": [
                [
                    "exercise_side",
                    "settlement_type",
                    "cash_settlement",
                    "physical_settlement",
                    "payment",
                    "clearing_instructions",
                ],
                ["is_exercisable"],
            ],
            "required": True,
        },
        {
            "options": [
                ["settlement_type"],
                ["cash_settlement"],
                ["physical_settlement"],
            ],
            "required": True,
        },
    ],
    "TradeChangeBase": [
        {
            "options": [
                ["trade_identifier"],
                ["original_trade"],
            ],
            "required": True,
        },
    ],
    "TradeChangeContent": [
        {
            "options": [
                ["old_trade_identifier"],
                ["old_trade"],
            ],
            "required": False,
        },
    ],
    "TradeIdentifier": [
        {
            "options": [
                ["issuer", "trade_id"],
                [
                    "trade_id",
                    "versioned_trade_id",
                    "party_reference",
                    "account_reference",
                ],
            ],
            "required": True,
        },
        {
            "options": [
                ["trade_id"],
                ["versioned_trade_id"],
            ],
            "required": True,
        },
    ],
    "TradeLegPriceChange": [
        {
            "options": [
                ["price_reference"],
                ["instrument_id"],
            ],
            "required": True,
        },
    ],
    "TradeLegSizeChange": [
        {
            "options": [
                [
                    "notional_reference",
                    "change_in_notional_amount",
                    "outstanding_notional_amount",
                ],
                [
                    "number_of_options_reference",
                    "change_in_number_of_options",
                    "outstanding_number_of_options",
                ],
                [
                    "number_of_units_reference",
                    "change_in_number_of_units",
                    "outstanding_number_of_units",
                ],
                [
                    "notional_schedule_reference",
                    "change_in_notional_schedule",
                    "outstanding_notional_schedule",
                ],
                [
                    "known_amount_reference",
                    "change_in_known_amount",
                    "outstanding_known_amount",
                ],
            ],
            "required": True,
        },
    ],
    "TradeNotionalChange": [
        {
            "options": [
                [
                    "change_in_notional_amount",
                    "outstanding_notional_amount",
                    "change_in_number_of_options",
                    "outstanding_number_of_options",
                    "change_in_number_of_units",
                    "outstanding_number_of_units",
                ],
                ["size_change"],
            ],
            "required": True,
        },
    ],
    "TradeNovationContent": [
        {
            "options": [
                ["new_trade_identifier", "new_trade"],
                [
                    "old_trade_identifier",
                    "old_trade",
                    "fee_trade_identifier",
                    "fee_trade",
                    "new_trade_identifier",
                    "new_trade",
                ],
                [
                    "fee_trade_identifier",
                    "fee_trade",
                    "new_trade_identifier",
                    "new_trade",
                ],
            ],
            "required": True,
        },
    ],
    "TradePackage": [
        {
            "options": [
                ["trade"],
                ["trade_reference_information"],
                ["trade_identifier"],
            ],
            "required": True,
        },
    ],
    "TradeReferenceInformation": [
        {
            "options": [
                ["originating_event"],
                ["terminating_event"],
            ],
            "required": False,
        },
    ],
    "TradeUnderlyer2": [
        {
            "options": [
                ["floating_rate"],
                ["fixed_rate"],
                ["exchange_rate"],
                ["basket"],
                ["bond"],
                ["cash"],
                ["commodity"],
                ["convertible_bond"],
                ["equity"],
                ["exchange_traded_fund"],
                ["future"],
                ["index"],
                ["loan"],
                ["mortgage"],
                ["mutual_fund"],
                ["option"],
                ["security"],
                ["warrant"],
                ["quoted_currency_pair"],
                ["reference_entity"],
                ["index_reference_information"],
                ["gas"],
                ["oil"],
                ["coal"],
                ["electricity"],
            ],
            "required": True,
        },
    ],
    "TransferFeeDefinition": [
        {
            "options": [
                ["payment_rule"],
                ["description"],
            ],
            "required": False,
        },
    ],
    "Trigger": [
        {
            "options": [
                ["level"],
                ["level_percentage"],
            ],
            "required": True,
        },
        {
            "options": [
                ["credit_events"],
                ["credit_events_reference"],
            ],
            "required": True,
        },
    ],
    "TriggerRateObservation": [
        {
            "options": [
                ["trigger_rate", "quoted_currency_pair", "observed_rate"],
                ["trigger_price", "observed_price"],
            ],
            "required": True,
        },
    ],
    "Underlyer": [
        {
            "options": [
                ["single_underlyer"],
                ["basket"],
            ],
            "required": True,
        },
    ],
    "UnderlyerInterestLeg": [
        {
            "options": [
                ["fixed_rate"],
                ["spread_schedule"],
            ],
            "required": False,
        },
    ],
    "ValuationDate": [
        {
            "options": [
                ["single_valuation_date"],
                ["multiple_valuation_dates"],
            ],
            "required": True,
        },
    ],
    "Variance": [
        {
            "options": [
                ["volatility_strike_price"],
                ["variance_strike_price"],
            ],
            "required": True,
        },
    ],
    "VarianceOptionTransactionSupplement": [
        {
            "options": [
                ["option_entitlement"],
                ["multiplier"],
            ],
            "required": False,
        },
    ],
    "VolatilityCap": [
        {
            "options": [
                ["total_volatility_cap"],
                ["volatility_cap_factor", "total_volatility_cap"],
            ],
            "required": False,
        },
    ],
    "VolatilityRepresentation": [
        {
            "options": [
                ["asset"],
                ["yield_curve_reference"],
            ],
            "required": True,
        },
    ],
    "VoteQuantity": [
        {
            "options": [
                ["vote_count"],
                ["vote_percent"],
                ["vote_amount"],
            ],
            "required": True,
        },
    ],
    "WeatherStation": [
        {
            "options": [
                ["weather_station_city"],
                ["weather_station_airport"],
                ["weather_station_wban"],
                ["weather_station_wmo"],
            ],
            "required": True,
        },
    ],
    "WeightedAveragingObservation": [
        {
            "options": [
                ["date_time"],
                ["observation_number"],
            ],
            "required": True,
        },
    ],
    "Withdrawal": [
        {
            "options": [
                ["party_trade_identifier", "party_trade_information"],
                ["trade"],
            ],
            "required": True,
        },
    ],
    "X509DataType": [
        {
            "options": [
                ["x509_issuer_serial"],
                ["x509_ski"],
                ["x509_subject_name"],
                ["x509_certificate"],
                ["x509_crl"],
            ],
            "required": True,
        },
    ],
}
